/** Define ids for each page. */
export const PAGE_IDS = {
  ADD_STUFF: 'add-stuff',
  BALANCE_SHEET: 'balance-sheet',
  EDIT_STUFF: 'edit-stuff',
  LANDING: 'landing',
  LIST_STUFF: 'list-stuff',
  LIST_STUFF_ADMIN: 'list-stuff-admin',
  MANAGE_DATABASE: 'manage-database',
  NOT_AUTHORIZED: 'not-authorized',
  NOT_FOUND: 'not-found',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
  DASHBOARD: 'dashboard',
  IMPORT: 'import',
  VERIFICATION_TABLE: 'verification-table',
  COMPARE_PROJECTIONS: 'compare-projections',
  USER_SETTINGS: 'user-settings',
  TOS: 'tos',
};
